### ISSUE TITLE
Attribute error raised when psycopg2 raises an exception on PyPy 5.0

### ISSUE THREAD

**Issue by thedrow** [chtd/psycopg2cffi#61]
Here's the traceback:
```
.tox/pypy-unit/site-packages/pytest_django/fixtures.py:54: in _django_db_setup
    interactive=False)
.tox/pypy-unit/site-packages/django/test/runner.py:726: in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
.tox/pypy-unit/site-packages/django/db/backends/base/creation.py:56: in create_test_db
    self._create_test_db(verbosity, autoclobber, keepdb)
.tox/pypy-unit/site-packages/django/db/backends/base/creation.py:165: in _create_test_db
    with self._nodb_connection.cursor() as cursor:
.tox/pypy-unit/site-packages/django/db/backends/base/creation.py:29: in _nodb_connection
    return self.connection._nodb_connection
.tox/pypy-unit/site-packages/django/db/backends/postgresql/base.py:239: in _nodb_connection
    nodb_connection.ensure_connection()
.tox/pypy-unit/site-packages/django/db/backends/base/base.py:199: in ensure_connection
    self.connect()
.tox/pypy-unit/site-packages/django/db/backends/base/base.py:171: in connect
    self.connection = self.get_new_connection(conn_params)
.tox/pypy-unit/site-packages/django/db/backends/postgresql/base.py:175: in get_new_connection
    connection = Database.connect(**conn_params)

.tox/pypy-unit/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy-unit/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy-unit/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
.tox/pypy-unit/site-packages/psycopg2cffi/_impl/connection.py:143: in _connect_sync
    raise self._create_exception()
AttributeError: 'Connection' object has no attribute '_py_enc'
```

It seems like it fails to encode the exception message so I'm not sure what the real exception is.

**Comment by lopuhin** [comment]
Hm, this could be a regression after #59 - if the error occurs before _py_enc was set up

**Comment by lopuhin** [comment]
If this is so, then you'll see the real exception by downgrading to ``psycopg2cffi==2.7.2``.

**Comment by thedrow** [comment]
Yes, that works. The exception message is caused by not having Postgres running when running the tests which is what I expect.

**Comment by thedrow** [comment]
Did you get a chance to look into this?

**Comment by lopuhin** [comment]
Opps, thanks for the reminder @thedrow , fixed now, 2.7.4 on pypi.

**Comment by thedrow** [comment]
You forgot to tag it.

**Comment by lopuhin** [comment]
Yeah, pushed the tag now, thanks!
